apiVersion: v2
name: klustered
description: A Helm chart for Kubernetes
type: application
home: https://github.com/nce/klustered
sources:
  - https://github.com/nce/klustered

version: 0.1.2
appVersion: "v1"
